apiVersion: apps/v1
kind: Deployment
metadata:
  name:  person-deployment
  namespace: dev
  labels:
    app:  person-deployment
    version: v1
spec:
  selector:
    matchLabels:
      app: person-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  person-deployment
    spec:
      containers:
      - name:  person-service
        image:  person:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        imagePullPolicy: IfNotPresent
        env:
          - name: address.url
            value: address-service.dev.svc.cluster.local:8081
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
          - containerPort: 8080